# CONNECTION STATUS CONSTANTS
CONNECTED = True
NOT_CONNECTED = False

# WAYPOINT STATUS CONSTANTS
WAYPOINT_INACTIVE = 100
WAYPOINT_ACTIVE = 101
WAYPOINT_COMPLETE = 102

# MISSION CONSTANTS
EXTREME_RETRIEVAL_DELIVERY = 200
SCIENCE = 201
AUTONOMOUS = 202
EQUIPMENT_SERVICING = 203 

# OPERATING MODE CONSTANTS
AUTONOMOUS_MODE = 300
DRIVER_CONTROL_MODE = 301

# LED STATUS CONSTANTS
OFF = 400
ON = 401
BLUE = 402
RED = 403
GREEN = 404

# DRIVE BASE ATTRIBUTES
