# CONNECTION STATUS CONSTANTS
CONNECTED = True
NOT_CONNECTED = False

# WAYPOINT STATUS CONSTANTS
WAYPOINT_INACTIVE = 0
WAYPOINT_ACTIVE = 1
WAYPOINT_COMPLETE = 2

# MISSION CONSTANTS
EXTREME_RETRIEVAL_DELIVERY = 0
SCIENCE = 1
AUTONOMOUS = 2
EQUIPMENT_SERVICING = 3 

# OPERATING MODE CONSTANTS
AUTONOMOUS_MODE = 0
DRIVER_CONTROL_MODE = 1

# LED STATUS CONSTANTS
OFF = 0
ON = 1
BLUE = 2
RED = 3
GREEN = 4