#ifndef PINOUT_H
#define PINOUT_H

enum STEPPER_PINS{
    SOILTRANSFER = 0,
    FLUROMETER = 1,
    SOILCOLLECTOR = 2
};

enum SOILTRANSFER_STEPPER_CONFIG{
    SOILTRANSFER_STEPPER_PIN0 = 0,
    SOILTRANSFER_STEPPER_PIN1 = 1,
    SOILTRANSFER_STEPPER_PIN2 = 2,
    SOILTRANSFER_STEPPER_PIN3 = 3,
    SOILTRANSFER_STEPPER_STEPS = 200
};

enum FLUROMETER_STEPPER_CONFIG{
    FLUROMETER_STEPPER_PIN0 = 0,
    FLUROMETER_STEPPER_PIN1 = 1,
    FLUROMETER_STEPPER_PIN2 = 2,
    FLUROMETER_STEPPER_PIN3 = 3,
    FLUROMETER_STEPPER_STEPS = 200
};

enum SOILCOLLECTOR_STEPPER_CONFIG{
    SOILCOLLECTOR_STEPPER_PIN0 = 0,
    SOILCOLLECTOR_STEPPER_PIN1 = 1,
    SOILCOLLECTOR_STEPPER_PIN2 = 2,
    SOILCOLLECTOR_STEPPER_PIN3 = 3,
    SOILCOLLECTOR_STEPPER_STEPS = 200
};

enum VIBRATOR_PINS{
    VIBRATOR_PIN0 = 0,
    VIBRATOR_PIN1 = 1,
    VIBRATOR_PIN2 = 2,
    VIBRATOR_PIN3 = 3,
    VIBRATOR_PIN4 = 4,
    VIBRATOR_PIN5 = 5,
};

#endif // PINOUT_H