#ifndef ENUM_LIST_H
#define ENUM_LIST_H

#include <FlexCAN_T4.h>

enum FLURO_POS{
    FLURO_POS0 = 0,
    FLURO_POS1 = 1,
    FLURO_POS2 = 2,
    FLURO_POS3 = 3,
    FLURO_POS4 = 4,
    FLURO_POS5 = 5,
};

enum SOIL_TRANSFER_POS{
    SOIL_TRANSFER_POS0 = 0,
    SOIL_TRANSFER_POS1 = 1,
    SOIL_TRANSFER_POS2 = 2,
    SOIL_TRANSFER_POS3 = 3,
    SOIL_TRANSFER_POS4 = 4,
    SOIL_TRANSFER_POS5 = 5,
};

enum TURN_DIRECTION{
    CLOCKWISE = 0,
    COUNTERCLOCKWISE = 1
};

enum CAN_MB{
    JETSON        = FLEXCAN_MAILBOX::MB0, 
    MAIN_BODY     = FLEXCAN_MAILBOX::MB1, 
    SCIENCE_BOARD = FLEXCAN_MAILBOX::MB2,
    ARM_BOARD     = FLEXCAN_MAILBOX::MB3
};

enum MICROPUMP_MODE{
    DISCRETE = 0,
    VARIABLE = 1
};

#endif